/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;

import dao.LoaiHangDAO;
import dao.MatHangDAO;
import entity.HoaDon;
import entity.LoaiHang;
import entity.MatHang;

/**
 *
 * @author hieud
 */
public class FrmMenu extends javax.swing.JFrame {
	private List<JpnItem> dspnmh;
	private HoaDon hd;
	private List<MatHang> dsmh;
	/**
	 * Creates new form FrmMenu
	 */
	private MatHangDAO matHangDAO;
	private List<LoaiHang> dslh;
	private LoaiHangDAO loaiHangDao;

	public FrmMenu(HoaDon hd) {
		this.hd = hd;
		dspnmh = new ArrayList<>();
		matHangDAO = new MatHangDAO();
		initComponents();
		try {
			dsmh = matHangDAO.layDanhSachMatHang();
			addControls();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		addDataCb();
	}

	private void addDataCb() {
		dslh = new ArrayList<>();
		loaiHangDao = new LoaiHangDAO();
		try {
			dslh = loaiHangDao.layDanhSachLoaiHang();
		} catch (Exception e) {
			e.printStackTrace();
		}
		StringBuilder sb = new StringBuilder();
		sb.append("Loại thức uống;");
		dslh.forEach(x -> sb.append(x.getTenLoaiHang()).append(";"));
		String[] content = sb.toString().split(";");
		cmbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(content));
	}

	private void addControls() throws Exception {
		loadPanel(dsmh);
		cmbLoaiSP.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					String loaiHang = cmbLoaiSP.getSelectedItem().toString();
					if (!loaiHang.equalsIgnoreCase("Loại thức uống"))
						loaiHang = loaiHangDao.timTheoTenLoaiHang(loaiHang).getMaLoaiHang();
					dsmh = matHangDAO.sapXepTheoLuaChon(loaiHang, cmbLoaiSP1.getSelectedItem().toString());
					loadPanel(dsmh);
				} catch (Exception e1) {
					e1.printStackTrace();
				}
			}
		});
		cmbLoaiSP1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					String loaiHang = cmbLoaiSP.getSelectedItem().toString();
					if (!loaiHang.equalsIgnoreCase("Loại thức uống"))
						loaiHang = loaiHangDao.timTheoTenLoaiHang(loaiHang).getMaLoaiHang();
					dsmh = matHangDAO.sapXepTheoLuaChon(loaiHang, cmbLoaiSP1.getSelectedItem().toString());
					loadPanel(dsmh);
				} catch (Exception e1) {
					e1.printStackTrace();
				}
				
			}
		});
	}

	private void loadPanel(List<MatHang> dsmh) throws Exception {
		pnlSanPham.removeAll();
		pnlSanPham.setLayout(new GridLayout(2, 8));
		JpnItem item;
		for (MatHang mh : dsmh) {
			item = new JpnItem(mh, hd);
			dspnmh.add(item);
			pnlSanPham.add(item);
		}
		pnlSanPham.repaint();
		pnlSanPham.validate();
		pnlSanPham.updateUI();
		panelItemControls();

	}

	public List<JpnItem> getDspnmh() {
		return dspnmh;
	}

	private void panelItemControls() {
		for (JpnItem i : dspnmh) {
			ActionListener listener = new ActionListener() {

				@Override
				public void actionPerformed(ActionEvent e) {

				}
			};
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		cmbLoaiSP = new javax.swing.JComboBox<>();
		jSeparator1 = new javax.swing.JSeparator();
		cmbLoaiSP1 = new javax.swing.JComboBox<>();
		jSeparator2 = new javax.swing.JSeparator();
		jScrollSanPham = new javax.swing.JScrollPane();
		pnlSanPham = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(230, 219, 209));

		cmbLoaiSP.setBackground(new java.awt.Color(230, 219, 209));
		cmbLoaiSP.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		cmbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại Thức Uống", " " }));
		cmbLoaiSP.setBorder(null);
		cmbLoaiSP.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cmbLoaiSPActionPerformed(evt);
			}
		});

		jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

		cmbLoaiSP1.setBackground(new java.awt.Color(230, 219, 209));
		cmbLoaiSP1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		cmbLoaiSP1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "A --> Z", "Z --> A", "Giá tăng dần", "Giá giảm dần", "Theo mã sản phẩm" }));
		cmbLoaiSP1.setBorder(null);

		jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

		javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
		pnlSanPham.setLayout(pnlSanPhamLayout);
		pnlSanPhamLayout.setHorizontalGroup(pnlSanPhamLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1336, Short.MAX_VALUE));
		pnlSanPhamLayout.setVerticalGroup(pnlSanPhamLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 697, Short.MAX_VALUE));

		jScrollSanPham.setViewportView(pnlSanPham);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(cmbLoaiSP, 0, 180, Short.MAX_VALUE).addComponent(jSeparator1))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(cmbLoaiSP1, 0, 180, Short.MAX_VALUE).addComponent(jSeparator2))
						.addGap(954, 954, 954))
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE)
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel1Layout.createSequentialGroup().addContainerGap()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(cmbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cmbLoaiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18).addComponent(jScrollSanPham, javax.swing.GroupLayout.DEFAULT_SIZE,
										699, Short.MAX_VALUE)
								.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void cmbLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	

	// Variables declaration - do not modify
	private javax.swing.JComboBox<String> cmbLoaiSP;
	private javax.swing.JComboBox<String> cmbLoaiSP1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollSanPham;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JPanel pnlSanPham;
	// End of variables declaration
}
