/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ScrollPaneConstants;

import dao.BanDAO;
import dao.BanHoaDonDao;
import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.NhanVienDAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.NhanVien;
import tablemodel.ChiTietHoaDonTableModel;

/**
 *
 * @author zombi
 */
public class JpnDatHang extends javax.swing.JPanel {
	private FrmMenu frmMenu;
	private HoaDon hd;
	private static final String[] HEADER = "Tên Sản Phẩm;Số Lượng;Đơn giá;Thành Tiền".split(";");
	private int soBan;
	private BanDAO banDao;

	private KhachHangDAO khachHangDAO;
	private NhanVienDAO nhanVienDAO;
	private HoaDonDAO hoaDonDAO;
	private JpnBanCon jpnBanCon;

	private ChiTietHoaDonTableModel chiTietHoaDonTableModel;
	private List<JpnBanCon> dsBanCon;
	private ChiTietHoaDonDAO chiTietHoaDonDAO;
	private List<ChiTietHoaDon> dscthd;
	private int maBanNow;
	private BanHoaDonDao banHoaDonDao;
	private NhanVien nv;
    /** Creates new form JpnDatHang */
    public JpnDatHang() {
		khachHangDAO = new KhachHangDAO();
		chiTietHoaDonDAO = new ChiTietHoaDonDAO();
		hoaDonDAO = new HoaDonDAO();
		nhanVienDAO = new NhanVienDAO();
		dsBanCon = new ArrayList<JpnBanCon>();
		dscthd = new ArrayList<>();
		banHoaDonDao = new BanHoaDonDao();
		banDao = new BanDAO();
        initComponents();
        addControls();
    }

    private void addControls() {
		jtbDonHang.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
		jtbDonHang.setRowHeight(30);
		jtbDonHang.setIntercellSpacing(new java.awt.Dimension(15, 0));

		jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
		jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);	
		BtnThem.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				frmMenu = new FrmMenu(hd);
				frmMenu.setLocationRelativeTo(null);
				frmMenu.setVisible(true);
				frmMenu.addWindowListener(new WindowListener() {

					@Override
					public void windowOpened(WindowEvent e) {
						// TODO Auto-generated method stub

					}

					@Override
					public void windowIconified(WindowEvent e) {
						// TODO Auto-generated method stub

					}

					@Override
					public void windowDeiconified(WindowEvent e) {
						// TODO Auto-generated method stub

					}

					@Override
					public void windowDeactivated(WindowEvent e) {
						// TODO Auto-generated method stub

					}

					@Override
					public void windowClosing(WindowEvent e) {
						try {
							if (hd != null)
								dscthd = chiTietHoaDonDAO.getChiTietHoaDonTheoMaHD(hd.getMaHoaDon());
							else
								dscthd = new ArrayList<>();
						} catch (Exception e1) {
							e1.printStackTrace();
						}
						updateModelTable(dscthd);

					}

					@Override
					public void windowClosed(WindowEvent e) {
						// TODO Auto-generated method stub

					}

					@Override
					public void windowActivated(WindowEvent e) {
						// TODO Auto-generated method stub

					}
				});
			}
		});
	}
	private void updateModelTable(List<ChiTietHoaDon> dscthd1) {
		chiTietHoaDonTableModel = new ChiTietHoaDonTableModel(HEADER, dscthd1);
		jtbDonHang.setModel(chiTietHoaDonTableModel);
		jtbDonHang.updateUI();
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDonHang = new javax.swing.JTable();
        plnChucNang = new javax.swing.JPanel();
        BtnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        BtnXuatHD = new javax.swing.JButton();
        jlbBan = new javax.swing.JLabel();
        tfBan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel3.setBackground(new java.awt.Color(230, 219, 209));

        jPanel2.setBackground(new java.awt.Color(230, 219, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Đơn Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jtbDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbDonHang);

        plnChucNang.setBackground(new java.awt.Color(230, 219, 209));
        plnChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        BtnThem.setBackground(new java.awt.Color(230, 219, 209));
        BtnThem.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BtnThem.setForeground(new java.awt.Color(102, 102, 102));
        BtnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Plus_30px.png"))); // NOI18N
        BtnThem.setText("Thêm");
        BtnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnXoa.setBackground(new java.awt.Color(230, 219, 209));
        btnXoa.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(102, 102, 102));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Recycle Bin_30px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        BtnXuatHD.setBackground(new java.awt.Color(230, 219, 209));
        BtnXuatHD.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        BtnXuatHD.setForeground(new java.awt.Color(102, 102, 102));
        BtnXuatHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/activity_history_30px.png"))); // NOI18N
        BtnXuatHD.setText("Thông tin khách hàng");
        BtnXuatHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout plnChucNangLayout = new javax.swing.GroupLayout(plnChucNang);
        plnChucNang.setLayout(plnChucNangLayout);
        plnChucNangLayout.setHorizontalGroup(
            plnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnChucNangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnXuatHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        plnChucNangLayout.setVerticalGroup(
            plnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnChucNangLayout.createSequentialGroup()
                .addGroup(plnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnThem)
                    .addComponent(btnXoa)
                    .addComponent(BtnXuatHD))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jlbBan.setBackground(new java.awt.Color(230, 219, 209));
        jlbBan.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jlbBan.setText("Bàn:");

        tfBan.setEditable(false);
        tfBan.setBackground(new java.awt.Color(230, 219, 209));
        tfBan.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        tfBan.setText("1");
        tfBan.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jlbBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfBan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(plnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBan)
                            .addComponent(tfBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(plnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnThem;
    private javax.swing.JButton BtnXuatHD;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbBan;
    private javax.swing.JTable jtbDonHang;
    private javax.swing.JPanel plnChucNang;
    private javax.swing.JTextField tfBan;
    // End of variables declaration                   

}
