/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;

import javax.swing.JOptionPane;

import dao.ChiTietHoaDonDAO;
import dao.MatHangDAO;
import entity.ChiTietHoaDon;
import entity.HoaDon;
import entity.MatHang;
import setting.PathSetting;

/**
 *
 * @author zombi
 */
public class JpnItem extends javax.swing.JPanel {

	/**
	 * Creates new form JpnItem
	 */
	private MatHang mh;
	private HoaDon hd;
	private ChiTietHoaDonDAO chiTietHoaDonDAO;
	private MatHangDAO matHangDAO;

	public JpnItem(MatHang mh, HoaDon hd) {
		this.mh = mh;
		this.hd = hd;
		matHangDAO = new MatHangDAO();
		chiTietHoaDonDAO = new ChiTietHoaDonDAO();
		initComponents();
		try {
			addControls();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void addControls() throws Exception {
		tfGia1.setText(mh.getTenMatHang());
		jlbSP1.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SANPHAM + mh.getLinkAnh()));
//    	DecimalFormat decimalFormat = new DecimalFormat("###,###,### đ");
		ChiTietHoaDon chiTietHoaDon = null;
		try {
			chiTietHoaDon = chiTietHoaDonDAO.timChiTietHoaDon(hd.getMaHoaDon(), mh.getMaMatHang());
		} catch (Exception e) {
			// TODO: handle exception
		}
		updateSoLuong(chiTietHoaDon);

		BtnThem1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				if (mh.getSoLuongTon()>0) {
					mh.setSoLuongTon(mh.getSoLuongTon()-1);
					try {
						ChiTietHoaDon cthd = new ChiTietHoaDon(mh, 1, hd);
						ChiTietHoaDon cthd1 = chiTietHoaDonDAO.timChiTietHoaDon(cthd.getMaHoaDon().getMaHoaDon(),
								cthd.getMaMatHang().getMaMatHang());
						if (cthd1 != null) {
							cthd.setSoLuong(cthd1.getSoLuong() + 1);
							chiTietHoaDonDAO.capNhanChiTietHoaDon(cthd);
							
						}
						else {
							chiTietHoaDonDAO.themChiTietHoaDon(cthd);
						}
						updateSoLuong(cthd);
						matHangDAO.capNhatMatHang(mh);
					} catch (Exception e1) {
						e1.printStackTrace();
					}
				}
				else {
					JOptionPane.showMessageDialog(null, "Sản phẩm này đã hết !!!");
				}
				
			}
		});
		BtnXoa.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				try {
					ChiTietHoaDon cthd = chiTietHoaDonDAO.timChiTietHoaDon(hd.getMaHoaDon(), mh.getMaMatHang());
					if (cthd.getSoLuong()>0)
					{
						cthd.setSoLuong(cthd.getSoLuong() - 1);
						if (cthd.getSoLuong()>0)
						chiTietHoaDonDAO.capNhanChiTietHoaDon(cthd);
						else chiTietHoaDonDAO.xoaChiTietHoaDon(cthd);
						updateSoLuong(cthd);
					}else {
						JOptionPane.showMessageDialog(null, "Số lượng phải >= 0","Lỗi số lượng", JOptionPane.ERROR_MESSAGE);
					}

				} catch (Exception e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
	}

	private void updateSoLuong(ChiTietHoaDon chiTietHoaDon) {
		int soLuong = 0;
		try {
			soLuong = chiTietHoaDon.getSoLuong();
		} catch (Exception e) {
			// TODO: handle exception
		}
		tfGia2.setText(soLuong + "");
		tfGia2.updateUI();
	}

	public void getActionBtnThem(ActionListener listener) {
		BtnThem1.addActionListener(listener);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jlbSP1 = new javax.swing.JLabel();
		tfGia1 = new javax.swing.JTextField();
		BtnThem1 = new javax.swing.JButton();
		tfGia2 = new javax.swing.JTextField();
		BtnXoa = new javax.swing.JButton();

		jlbSP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/no-image.jpg"))); // NOI18N

		tfGia1.setEditable(false);
		tfGia1.setBackground(new java.awt.Color(230, 219, 209));
		tfGia1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		tfGia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tfGia1.setText("coffee sữa đá");
		tfGia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		BtnThem1.setBackground(new java.awt.Color(230, 219, 209));
		BtnThem1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		BtnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Plus_20px.png"))); // NOI18N
		BtnThem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		tfGia2.setEditable(false);
		tfGia2.setBackground(new java.awt.Color(230, 219, 209));
		tfGia2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		tfGia2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tfGia2.setText("0");
		tfGia2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		BtnXoa.setBackground(new java.awt.Color(230, 219, 209));
		BtnXoa.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
		BtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minus_20px.png"))); // NOI18N
		BtnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
		BtnXoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BtnThem2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(tfGia1, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addComponent(BtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tfGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(BtnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jlbSP1, javax.swing.GroupLayout.Alignment.TRAILING))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jlbSP1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(tfGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(tfGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BtnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(BtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>

	private void BtnThem2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton BtnThem1;
	private javax.swing.JButton BtnXoa;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JLabel jlbSP1;
	private javax.swing.JTextField tfGia1;
	private javax.swing.JTextField tfGia2;
	// End of variables declaration
}
