/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import entity.NhanVien;
import setting.PathSetting;

/**
 *
 * @author hieud
 */
public class JpnTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form JpnTaiKhoan
     */
	private FrmDoiMatKhau frmDMK ;
	private NhanVien nv;
    public JpnTaiKhoan(NhanVien nv) {
    	this.nv = nv;
    	frmDMK = new FrmDoiMatKhau(nv);
        initComponents();
        addControls();
    }

    private void addControls() {
    	tfHoTen.setText(nv.getTenNhanVien());
    	tfChucVu.setText(nv.getChucVu());
    	tfMaNV.setText(nv.getMaNhanVien());
    	DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    	tfNgaySinh.setText(df.format(nv.getNgaySinh()));
    	tfGioiTinh.setText((nv.isGioiTinh()?"Nam":"Nữ"));
    	System.out.println(nv.isGioiTinh());
    	tfNgayVaoLam.setText(df.format(nv.getNgayVaoLam()));
    	tfSDT.setText(nv.getSoDienThoai());
    	tfChucVu.setText(nv.getChucVu());
    	jlbAnh.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + nv.getLinkAnhNV()));
    	btnDoiMK.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				frmDMK.setVisible(true);
			}
		});
    	
	}
    public void btnDangXuatAddActionListener(ActionListener listener) {
    	btnDangXuat.addActionListener(listener);
    }
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plnTK1 = new javax.swing.JPanel();
        jlbMaNV = new javax.swing.JLabel();
        tfMaNV = new javax.swing.JTextField();
        jlbNgaySinh = new javax.swing.JLabel();
        tfHoTen = new javax.swing.JTextField();
        jlbngaySinh = new javax.swing.JLabel();
        tfNgaySinh = new javax.swing.JTextField();
        jlbGioiTinh = new javax.swing.JLabel();
        tfGioiTinh = new javax.swing.JTextField();
        jlbNgayVaoLam = new javax.swing.JLabel();
        tfNgayVaoLam = new javax.swing.JTextField();
        jlbChucVu = new javax.swing.JLabel();
        jlbSDT = new javax.swing.JLabel();
        tfSDT = new javax.swing.JTextField();
        tfChucVu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        plnTK2 = new javax.swing.JPanel();
        plnAnh = new javax.swing.JPanel();
        jlbAnh = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnDoiMK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        plnTK1.setBackground(new java.awt.Color(230, 219, 209));

        jlbMaNV.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbMaNV.setText("Mã Nhân Viên:");

        tfMaNV.setEditable(false);
        tfMaNV.setBackground(new java.awt.Color(230, 219, 209));
        tfMaNV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfMaNV.setText("NV01");
        tfMaNV.setBorder(null);

        jlbNgaySinh.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbNgaySinh.setText("Họ Và Tên:");

        tfHoTen.setEditable(false);
        tfHoTen.setBackground(new java.awt.Color(230, 219, 209));
        tfHoTen.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfHoTen.setText("Cao Nguyễn Gia Hưng");
        tfHoTen.setBorder(null);

        jlbngaySinh.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbngaySinh.setText("Ngày Sinh:");

        tfNgaySinh.setEditable(false);
        tfNgaySinh.setBackground(new java.awt.Color(230, 219, 209));
        tfNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfNgaySinh.setText("04/04/2002");
        tfNgaySinh.setBorder(null);

        jlbGioiTinh.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbGioiTinh.setText("Giới Tính:");

        tfGioiTinh.setEditable(false);
        tfGioiTinh.setBackground(new java.awt.Color(230, 219, 209));
        tfGioiTinh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfGioiTinh.setText("Nam");
        tfGioiTinh.setBorder(null);

        jlbNgayVaoLam.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbNgayVaoLam.setText("Ngày Vào Làm:");

        tfNgayVaoLam.setEditable(false);
        tfNgayVaoLam.setBackground(new java.awt.Color(230, 219, 209));
        tfNgayVaoLam.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfNgayVaoLam.setText("01/01/2020");
        tfNgayVaoLam.setBorder(null);

        jlbChucVu.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbChucVu.setText("Chức Vụ:");

        jlbSDT.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jlbSDT.setText("Số Điện Thoại:");

        tfSDT.setEditable(false);
        tfSDT.setBackground(new java.awt.Color(230, 219, 209));
        tfSDT.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfSDT.setText("0347825051");
        tfSDT.setBorder(null);

        tfChucVu.setEditable(false);
        tfChucVu.setBackground(new java.awt.Color(230, 219, 209));
        tfChucVu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tfChucVu.setText("Nhân Viên");
        tfChucVu.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout plnTK1Layout = new javax.swing.GroupLayout(plnTK1);
        plnTK1.setLayout(plnTK1Layout);
        plnTK1Layout.setHorizontalGroup(
            plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTK1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbSDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfHoTen))
                    .addGroup(plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbNgayVaoLam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(tfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator8)
                    .addGroup(plnTK1Layout.createSequentialGroup()
                        .addComponent(jlbChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        plnTK1Layout.setVerticalGroup(
            plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTK1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaNV)
                    .addComponent(tfMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNgaySinh)
                    .addComponent(tfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbngaySinh)
                    .addComponent(tfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGioiTinh)
                    .addComponent(tfGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNgayVaoLam)
                    .addComponent(tfNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSDT)
                    .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(plnTK1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbChucVu)
                    .addComponent(tfChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plnTK2.setBackground(new java.awt.Color(230, 219, 209));

        jlbAnh.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_NHANVIEN + "\\hung.png")); // NOI18N

        javax.swing.GroupLayout plnAnhLayout = new javax.swing.GroupLayout(plnAnh);
        plnAnh.setLayout(plnAnhLayout);
        plnAnhLayout.setHorizontalGroup(
            plnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        plnAnhLayout.setVerticalGroup(
            plnAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnAnhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDangXuat.setBackground(new java.awt.Color(230, 219, 209));
        btnDangXuat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(51, 51, 51));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SYSTEM + "\\logout_30px.png")); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnDoiMK.setBackground(new java.awt.Color(230, 219, 209));
        btnDoiMK.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(51, 51, 51));
        btnDoiMK.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SYSTEM + "\\Refresh_30px.png")); // NOI18N
        btnDoiMK.setText("Đổi Mật Khẩu");
        btnDoiMK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout plnTK2Layout = new javax.swing.GroupLayout(plnTK2);
        plnTK2.setLayout(plnTK2Layout);
        plnTK2Layout.setHorizontalGroup(
            plnTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plnTK2Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(plnTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plnTK2Layout.createSequentialGroup()
                        .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        plnTK2Layout.setVerticalGroup(
            plnTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnTK2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(plnAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(plnTK2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SYSTEM + "\\centerr2.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnTK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(plnTK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plnTK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plnTK1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlbAnh;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbGioiTinh;
    private javax.swing.JLabel jlbMaNV;
    private javax.swing.JLabel jlbNgaySinh;
    private javax.swing.JLabel jlbNgayVaoLam;
    private javax.swing.JLabel jlbSDT;
    private javax.swing.JLabel jlbngaySinh;
    private javax.swing.JPanel plnAnh;
    private javax.swing.JPanel plnTK1;
    private javax.swing.JPanel plnTK2;
    private javax.swing.JTextField tfChucVu;
    private javax.swing.JTextField tfGioiTinh;
    private javax.swing.JTextField tfHoTen;
    private javax.swing.JTextField tfMaNV;
    private javax.swing.JTextField tfNgaySinh;
    private javax.swing.JTextField tfNgayVaoLam;
    private javax.swing.JTextField tfSDT;
    // End of variables declaration//GEN-END:variables
}
