package gui;

import java.awt.event.ActionListener;

import setting.PathSetting;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author hung
 */

public class PanelXacNhan extends javax.swing.JPanel {

    /**
     * Creates new form jpnThem
     * @param opt 
     */
    public PanelXacNhan() {
        initComponents();

 
    }


	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void huyAddActionListener(ActionListener listener) {
    	btnHuy.addActionListener(listener);
    }
    public void xacNhanAddActionListener(ActionListener listener) {
    	btnXacNhan.addActionListener(listener);
    }
    private void initComponents() {

        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 219, 209));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        btnXacNhan.setBackground(new java.awt.Color(230, 219, 209));
        btnXacNhan.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(102, 102, 102));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SYSTEM + "\\done_30px.png")); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnHuy.setBackground(new java.awt.Color(230, 219, 209));
        btnHuy.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(102, 102, 102));
        btnHuy.setIcon(new javax.swing.ImageIcon(PathSetting.PATH_IMAGE_SYSTEM + "\\close_30px.png")); // NOI18N
        btnHuy.setText("Thoát");
        btnHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    // End of variables declaration//GEN-END:variables
}
// End of variables declaration//GEN-END:variables
